# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/kamouh/vivado_project/project_fifo_comClk_ram/project_fifo_comClk_ram.cache/wt [current_project]
set_property parent.project_path C:/Users/kamouh/vivado_project/project_fifo_comClk_ram/project_fifo_comClk_ram.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.2 [current_project]
read_ip c:/Users/kamouh/vivado_project/project_fifo_comClk_ram/project_fifo_comClk_ram.srcs/sources_1/ip/fifo/fifo.xci
set_property is_locked true [get_files c:/Users/kamouh/vivado_project/project_fifo_comClk_ram/project_fifo_comClk_ram.srcs/sources_1/ip/fifo/fifo.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file fifo.hwdef }
synth_design -top fifo -part xc7z020clg484-1 -mode out_of_context
rename_ref -prefix_all fifo_
write_checkpoint -noxdef fifo.dcp
catch { report_utilization -file fifo_utilization_synth.rpt -pb fifo_utilization_synth.pb }
if { [catch {
  file copy -force C:/Users/kamouh/vivado_project/project_fifo_comClk_ram/project_fifo_comClk_ram.runs/fifo_synth_1/fifo.dcp c:/Users/kamouh/vivado_project/project_fifo_comClk_ram/project_fifo_comClk_ram.srcs/sources_1/ip/fifo/fifo.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub c:/Users/kamouh/vivado_project/project_fifo_comClk_ram/project_fifo_comClk_ram.srcs/sources_1/ip/fifo/fifo_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub c:/Users/kamouh/vivado_project/project_fifo_comClk_ram/project_fifo_comClk_ram.srcs/sources_1/ip/fifo/fifo_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim c:/Users/kamouh/vivado_project/project_fifo_comClk_ram/project_fifo_comClk_ram.srcs/sources_1/ip/fifo/fifo_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim c:/Users/kamouh/vivado_project/project_fifo_comClk_ram/project_fifo_comClk_ram.srcs/sources_1/ip/fifo/fifo_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
