# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx.xci
# IP: The module: 'fifo_tx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx/fifo_tx.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tx'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx.xci
# IP: The module: 'fifo_tx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx/fifo_tx.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
