# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc702:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

read_ip /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx.xci
set_property used_in_implementation false [get_files /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx.dcp]
set_property used_in_implementation false [get_files -all /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx.dcp]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.cache/wt [current_project]
set_property parent.project_dir /tp/xph3sle/xph3sle508/project_NI/project_FIFO [current_project]
synth_design -top fifo_tx -part xc7z020clg484-1 -mode out_of_context

rename_ref -prefix_all fifo_tx
write_checkpoint -noxdef fifo_tx.dcp
report_utilization -file fifo_tx_utilization_synth.rpt -pb fifo_tx_utilization_synth.pb
if { [catch {
  file copy -force /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.runs/fifo_tx_synth_1/fifo_tx.dcp /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx.dcp
  write_verilog -force -mode synth_stub /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx_stub.v
  write_vhdl -force -mode synth_stub /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx_stub.vhdl
  write_verilog -force -mode funcsim /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx_funcsim.v
  write_vhdl -force -mode funcsim /tp/xph3sle/xph3sle508/project_NI/project_FIFO/project_FIFO.srcs/sources_1/ip/fifo_tx/fifo_tx_funcsim.vhdl
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy supporting IP files."
}
