# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc702:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files -quiet /tp/xph3sle/xph3sle508/project_NI/codes/project_FIFO/project_FIFO.runs/fifo_tx_synth_1/fifo_tx.dcp
set_property used_in_implementation false [get_files /tp/xph3sle/xph3sle508/project_NI/codes/project_FIFO/project_FIFO.runs/fifo_tx_synth_1/fifo_tx.dcp]
read_vhdl -library xil_defaultlib /tp/xph3sle/xph3sle508/project_NI/codes/project_FIFO/project_FIFO.srcs/sources_1/new/tx.vhd
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /tp/xph3sle/xph3sle508/project_NI/codes/project_FIFO/project_FIFO.cache/wt [current_project]
set_property parent.project_dir /tp/xph3sle/xph3sle508/project_NI/codes/project_FIFO [current_project]
synth_design -top tx -part xc7z020clg484-1
write_checkpoint tx.dcp
report_utilization -file tx_utilization_synth.rpt -pb tx_utilization_synth.pb
